# Generated by Django 5.0 on 2023-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hashtag',
            field=models.CharField(default='news', max_length=100),
        ),
    ]
